"""empty message

Revision ID: 56fe7547a867
Revises: None
Create Date: 2015-10-02 23:09:47.740860

"""

# revision identifiers, used by Alembic.
revision = '56fe7547a867'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('posts')
    op.add_column('groceries', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'groceries', 'users', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'groceries', type_='foreignkey')
    op.drop_column('groceries', 'author_id')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=u'posts_pkey')
    )
    op.drop_table('users')
    ### end Alembic commands ###
